from __future__ import annotations

from scripts.generate_whats_new import collect_entries, render_yaml, to_czech_title


def test_to_czech_title_known_phrases():
    assert "měřítko" in to_czech_title(
        "Replace map-type preset with scale and contour selects (v1.8)."
    ).casefold()
    veg = to_czech_title(
        "Fix color_map population in ensure_isom_color (fixes black vegetation in MTBO)"
    )
    assert "vegetace" in veg.casefold() or veg.startswith("Oprava")
    assert to_czech_title("fix: something broke").startswith("Oprava:")
    # Anglické „symbol“ nesmí vypnout překlad (dřív false positive v _looks_czech).
    bridge = to_czech_title(
        "Draw sprint OSM bridges as the connecting path symbol, not 512.1."
    )
    assert "most" in bridge.casefold()
    assert not bridge.startswith("Draw")


def test_collect_entries_from_git():
    entries = collect_entries(since_days=60, max_entries=5)
    assert isinstance(entries, list)
    if entries:
        assert "date" in entries[0]
        assert "title" in entries[0]
        assert entries[0]["title"]
        title = entries[0]["title"]
        assert any(
            ch in title for ch in "áčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ"
        ) or title.startswith(
            (
                "Oprava",
                "Novinka",
                "Přidáno",
                "Úprava",
                "Změna",
                "Aktualizace",
                "Odstranění",
                "Dokumentace",
                "Refaktor",
                "Sprint",
                "Budovy",
                "Krátké",
                "MTBO",
                "Více",
                "Tři",
                "Symbolové",
                "ZABAGED",
                "Přehled",
                "Měřítko",
                "Posunutí",
                "Úklid",
            )
        )


def test_render_yaml_marks_autogenerated():
    text = render_yaml(
        "2026-09-16T12:00:00Z",
        [{"date": "2026-09-16", "title": "Test change", "body": ""}],
    )
    assert "AUTO-GENERATED" in text
    assert "Test change" in text
    assert "2026-09-16T12:00:00Z" in text
