from __future__ import annotations

from scripts.generate_whats_new import collect_entries, render_yaml


def test_collect_entries_from_git():
    entries = collect_entries(since_days=60, max_entries=5)
    assert isinstance(entries, list)
    if entries:
        assert "date" in entries[0]
        assert "title" in entries[0]
        assert entries[0]["title"]


def test_render_yaml_marks_autogenerated():
    text = render_yaml(
        "2026-09-16T12:00:00Z",
        [{"date": "2026-09-16", "title": "Test change", "body": "Detail."}],
    )
    assert "AUTO-GENERATED" in text
    assert "Test change" in text
    assert "2026-09-16T12:00:00Z" in text
