# Podkladarna base pullauta.ini (preset keys overridden by ini_builder.py)
#------------------------------------------------------#
# Parameters for the Karttapullautin pullautus process #
#----------------------------------------------------- #

undergrowth=0.35
undergrowth2=0.56
greenground=0.9
greenhigh=2
topweight=0.80
vegezoffset=0
greendetectsize=2
zone1=1.0|2.65|99|1
zone2=2.65|3.4|99|0.1
zone3=3.4|5.5|8|0.2
thresold1=0.20|3|0.1
thresold2=3|4|0.1
thresold3=4|7|0.1
thresold4=7|20|0.1
thresold5=20|99|0.1
pointvolumefactor=0.1
pointvolumeexponent=1
firstandlastreturnfactor=1
lastreturnfactor =1
firstandlastreturnasground=3
greenshades=0.2|0.35|0.5|0.7|1.3|2.6|4|99|99|99|99
lightgreentone=200
greendotsize=0
groundboxsize=1
medianboxsize=6
medianboxsize2=1
yellowheight=0.9
yellowthresold=0.9
cliff1 = 1.4
cliff2 = 2.8
cliffthin=1
cliffsteepfactor=0.38
cliffflatplace=3.5
cliffnosmallciffs=5.5
cliffdebug=0
northlinesangle=0
northlineswidth=0
formline=2
formlinesteepness=0.37
formlineaddition=17
minimumgap = 30
dashlength = 60
gaplength =12
indexcontours=12.5
smoothing = 0.85
curviness=1.1
knolls=0.6
coordxfactor=1
coordyfactor=1
coordzfactor=1
thinfactor = 1
# waterelevation=0.3
# buildingsclass=6
detectbuildings=0
batch=0
processes=2
batchoutfolder=./out
lazfolder=./in
vectorconf=zabaged.txt
mtkskiplayers=
buildingcolor=0,0,0
savetempfiles=0
savetempfolders=0
basemapinterval=1.25
contour_interval=5
depression_length=181
yellow_smoothing=0
yellowmedianboxsize=0
vege_bitmode=0
label_formlines_depressions=0
remove_touching_contours=0
vegeonly=0
contoursonly=0
cliffsonly=0
output_dxf=1
parallel_laz_decompression=1
experimental_use_in_memory_fs=0
scalefactor=0.75
zoffset=0
