layers:
  - BudovaJednotlivaNeboBlokBudov
  - KulnaSklenikFoliovnikPristresek
  - ArealUceloveZastavby
  - RozvalinaZricenina
  - VezovitaStavba
  - StavebniObjektZakryty
  - Tribuna
  - VodniPlocha
  - VodniTok
  - SilniceDalnice
  - Cesta
  - Most
  - Ulice
  - Pesina
  - Lavka
  - Tunel
  - Podjezd
  - TramvajovaDraha
  - ZeleznicniTrat
  - ZeleznicniVlecka
  - Koleiste
  - ArealZeleznicniStanice
  - LanovaDrahaLyzarskyVlek
  - StozarLanoveDrahy
  - KrizSloupKulturnihoVyznamu
  - MohylaPomnikNahrobek
  - StupenSraz
  - Zed
  - HradbaVal
  - ElektrickeVedeni
  - Hrbitov
  - ParkovisteOdpocivka
  - SkupinaBalvanu
  - OsamelyBalvanSkalaSkalniSuk
  - Zabrana
  - OvocnySadZahrada
  - UdrzovanaZelen
  - OstatniPlochaVSidlech
  - OrnaPudaAOstatniDaleNespecifikovanePlochy
  - TrvalyTravniPorost
  - LesniPudaSKrovinatymPorostem
  - VyznamnyStromLesik
  - LiniovaVegetace
